class Family {
  String MembershipId,
      MemberType,
      MainMemberId,
      FirstName,
      MiddleName,
      LastGautra,
      Height;
  String Mobile1,
      Mobile2,
      Mobile3,
      Photo,
      Education,
      Education_id,
      OtherEducationName,
      SpecialInfo,
      BloodGroup,
      EmailId;
  String DOB, IncomeLevel, Relation, ProfessionId, NativeId;
  String NanihalGautra, NanihalNative, NanihalNative_id, NanihalBusiness;
  String SasuralGautra,
      SasuralNative,
      SasuralNative_id,
      SasuralBusiness,
      Gender,
      Married,
      AniversaryDate;
  String OfficeCompanyName,OfficeWorkType,Officedesignation,OfficeSince,OfficeBlock1, OfficeBlock2, OfficeBlock3;
  String ResidanceAddress,
      ResidanceLandmark,
      ResidenaceCityId,
      ResidanceMobile,
      ResidanceTelephone,
      ResidancePincode;
  String OfficeFirmName,
      OfficeWebsite,
      OfficeEmailId,
      OfficeAddress,
      OfficeLandmark,
      OfficeCityId,
      OfficeMobile,
      OfficeTelephone,
      OfficePincode;
  String NativeOffice,
      NativeLandmark,
      NativeCityId,
      NativeMobile,
      NativeTelephone,
      NativePincode,
      NativeName;
  String RecName1, RecName2, TrusteeName;
  String FormNumber, rcity, rstate, ostate, ocity, nstate, ncity;

  Family({
    this.MembershipId,
    this.FirstName,
    this.MiddleName,
    this.LastGautra,
    this.Height,
    this.Mobile1,
    this.Photo,
    this.Education,
    this.Education_id,
    this.OtherEducationName,
    this.SpecialInfo,
    this.BloodGroup,
    this.EmailId,
    this.DOB,
    this.IncomeLevel,
    this.MemberType,
    this.MainMemberId,
    this.Relation,
    this.Mobile2,
    this.Mobile3,
    this.ProfessionId,
    this.NativeId,
    this.NanihalNative,
    this.NanihalNative_id,
    this.NanihalBusiness,
    this.SasuralGautra,
    this.SasuralNative,
    this.SasuralNative_id,
    this.Gender,
    this.Married,
    this.AniversaryDate,
    this.ResidanceLandmark,
    this.ResidenaceCityId,
    this.ResidanceMobile,
    this.ResidanceTelephone,
    this.ResidancePincode,
    this.OfficeBlock1,
    this.OfficeBlock2,
    this.OfficeBlock3,
    this.OfficeFirmName,
    this.OfficeWebsite,
    this.OfficeEmailId,
    this.OfficeAddress,
    this.OfficeLandmark,
    this.OfficeSince,
    this.OfficeCityId,
    this.OfficeMobile,
    this.OfficeTelephone,
    this.OfficePincode,
    this.NativeOffice,
    this.NativeLandmark,
    this.NativeCityId,
    this.NativeMobile,
    this.NativeTelephone,
    this.NativePincode,
    this.NativeName,
    this.RecName1,
    this.RecName2,
    this.TrusteeName,
    this.ResidanceAddress,
    this.SasuralBusiness,
    this.NanihalGautra,
    this.FormNumber,
    this.rcity,
    this.rstate,
    this.ostate,
    this.ocity,
    this.nstate,
    this.ncity,
    this.OfficeCompanyName,
    this.OfficeWorkType,
    this.Officedesignation
  });

  factory Family.fromJson(Map<String, dynamic> json) {
    return Family(
      MembershipId: json['MembershipId'],
      Relation: json['Relation'],
      FirstName: json['FirstName'],
      MiddleName: json['MiddleName'],
      LastGautra: json['LastGautra'],
      Height: json['UnMHeight'],
      Mobile1: json['Mobile1'],
      Photo: json['Photo'],
      Education: json['EducationName'],
      Education_id: json["Education_id"],
      OtherEducationName: json['OtherEducationName'],
      SpecialInfo: json['SpecialInfo'],
      BloodGroup: json['BloodGroup'],
      EmailId: json['Emaild'],
      DOB: json['DOB'],
      IncomeLevel: json['PovLevel'],
      MemberType: json['MemberType'],
      MainMemberId: json['MainMemberId'],
      Mobile2: json['Mobile2'],
      Mobile3: json['Mobile3'],
      ProfessionId: json['ProfessionId'],
      NativeId: json['NativeId'],
      NanihalGautra: json['NanihalGautra'],
      NanihalNative: json['NNativeName'],
      NanihalNative_id: json['NanihalNative_id'],
      NanihalBusiness: json['NanihalBusiness'],
      SasuralGautra: json['SasuralGautra'],
      SasuralNative: json['SNativeName'],
      SasuralNative_id: json['SasuralNative_id'],
      SasuralBusiness: json['SasuralBusiness'],
      Gender: json['Gender'],
      Married: json['Married'],
      AniversaryDate: json['AniversaryDate'],
      ResidanceAddress: json['ResidanceAddress'],
      ResidanceLandmark: json['ResidanceLandmark'],
      ResidenaceCityId: json['ResidenaceCityId'],
      ResidanceMobile: json['ResidanceMobile'],
      ResidanceTelephone: json['ResidanceTelephone'],
      ResidancePincode: json['ResidancePincode'],
      OfficeWorkType: json['OfficeWorkType'],
      OfficeFirmName: json['OfficeFirmName'],
      OfficeWebsite: json['OfficeWebsite'],
      OfficeEmailId: json['OfficeEmailId'],
      OfficeBlock1: json['OfficeBlock1'],
      OfficeBlock2: json['OfficeBlock2'],
      OfficeBlock3: json['OfficeBlock3'],
      OfficeAddress: json['OfficeAddress'],
      OfficeLandmark: json['OfficeLandmark'],
      OfficeCompanyName: json['OfficeCompanyName'],
      Officedesignation: json['Officedesignation'],
      OfficeSince: json['OfficeSince'],
      OfficeCityId: json['OfficeCityId'],
      OfficeMobile: json['OfficeMobile'],
      OfficeTelephone: json['OfficeTelephone'],
      OfficePincode: json['OfficePincode'],
      NativeOffice: json['NativeOffice'],
      NativeLandmark: json['NativeLandmark'],
      NativeCityId: json['NativeCityId'],
      NativeMobile: json['NativeMobile'],
      NativeTelephone: json['NativeTelephone'],
      NativePincode: json['NativePincode'],
      NativeName: json['NativeName'],
      RecName1: json['RecName1'],
      RecName2: json['RecName2'],
      TrusteeName: json['TrusteeName'],
      FormNumber: json['FormNumber'],
      rcity: json['rcity'],
      rstate: json['rstate'],
      ostate: json['ostate'],
      ocity: json['ocity'],
      nstate: json['nstate'],
      ncity: json['ncity'],
    );
  }
}
